name: github pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment

jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate documentation
        run: |
          sphinx-build -b html ./ ./build/docs/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs/